### ISSUE TITLE
Firefox-profile prevents closing application on Ctrl+C

### ISSUE THREAD

**Issue by aa6** [saadtazi/firefox-profile-js#73]
```coffeescript
co = require "co"
sleep = require "co-sleep"
firefox_profile = require "firefox-profile"

co ->
  profile = new firefox_profile()
  console.log "Try Ctrl+C to close me."
  yield sleep(10000000)
```

**Comment by saadtazi** [comment]
This is so true! I fix is on its way...

**Comment by saadtazi** [comment]
I just released 0.4.5 to fix this issue. Closing, but feel free to reopen if needed.

**Comment by kolontsov** [comment]
And now you're preventing user code to return anything except 0 in exit code (as indication of failed mocha tests, for example), because you're setting process.on('exit') handler which always does process.exit(0). Also, your SIGINT handler does process.exit(130) which is also intercepted by your on('exit').

Looks catastrophic enough.

**Comment by saadtazi** [comment]
What a disaster! Sorry about that. Lt me know if you think #76 addresses the issue you mentioned. I published it as v0.4.6 (better than v0.4.5).

**Comment by kolontsov** [comment]
Yes, bug is fixed (just tested it on our mocha/webdriverio/selenium). Thank you for a such quick response!

**Comment by saadtazi** [comment]
Great! Thanks, for reporting and... and for checking that it's fixed!
