### ISSUE TITLE
Your connection is not secure

### ISSUE THREAD

**Issue by mathew-kurian** [saadtazi/firefox-profile-js#75]
``` js
profile.setAssumeUntrustedCertIssuer(false);
profile.setAcceptUntrustedCerts(true);
```

Even after setting these options, I get the following error:

```
Your connection is not secure

The owner has configured their website improperly. To protect your information from being stolen, Firefox has not connected to this website.
```

**Comment by saadtazi** [comment]
Hi,
Can you please share the browser used (`firefox` I guess, based on the error message...), the browser version and selenium "server" type (standalone vs geckdriver).

If you are using firefox, I think that the new firefox (50+) requires [`geckodriver`](https://github.com/mozilla/geckodriver/) instead of `selenium-server-standalone`.

If you are using geckodriver, then you might be interested by [this geckodriver issue](https://github.com/mozilla/geckodriver/issues/93).

Thank you!

**Comment by saadtazi** [comment]
The geckodriver issue is closed, so this is probably fixed (To be confirmed...)
